data = float(input("Введите число: "))
data_int = int(data)
left, right = divmod(data_int, 1000)
res1, res2 = divmod(right, 100)
res3, res4 = divmod(res2, 10)
res5, res6 = divmod(res4, 1)
print(left)
print(res1)
print(res3)
print(res5)